#app

##spring
#spring:
#  # H2 DATABASE CONFIG
#  datasource:
#    url: jdbc:mysql://${cms.database.host}:${cms.database.post}/${cms.database.name}?serverTimezone=UTC
#    username: ${cms.database.username}
#    password: ${cms.database.password}
#    type: org.apache.commons.dbcp2.BasicDataSource
#    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sunlands.dragnet.cms.*.opport,com.sunlands.dragnet.*.dto,com.sunlands.dragnet.*.vo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0

   #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false

#cas
cas:
  casServer: ${cas.casserver}
  serverName: ${cas.currentappurl}
  ignoreAddress: ${cas.ignoreaddress}
  switch: ${cas.switch}

img:
  upload:
    url: ${img.upload.url}
    channelCode: ${img.upload.channelCode}

growth:
  url: ${growth.url}

logging:
  path: ${log.path}

ehr:
  url: ${ehr.url}
  key: ${ehr.key}
  systemName: ${ehr.systemname}


db:
  mongodb:
    host: ${db.mongodb.host}
    port: ${db.mongodb.port}
    databaseName: ${db.mongodb.databaseName}
    collectionName: ${db.mongodb.collectionName}

