#读写分离配置
sharding.jdbc:
  data-sources:
    cms_master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.247.62.90:3306/cms?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    cms_slave_0:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.247.62.90:3306/cms?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  master-slave-rule:
    name: cms_ms
    master-data-source-name: cms_master
    slave-data-source-names: cms_slave_0
    load-balance-algorithm-type: round_robin



spring:
  profiles: dev

             `
log:
  path: e:\log-cms\cms
